#!/bin/bash

# Collects docker containers/volumes
# not used in the last 7 days.

collect_old_containers_and_volumes()
{
  local pattern=$1
  local cids=$(docker ps --quiet --all --filter "name=${pattern}")
  local now=$(date)
  local count=$(echo ${cids} | wc -w)
  echo "${now}: cyber-dojo collector checking ${count} ${2} containers"

  for cid in ${cids}; do
    changers=$(docker exec -it ${cid} sh -c "find /sandboxes/** -mtime -7")
    if [ "${changers}" = "" ]; then
      docker ps --all --filter "name=${name}" | grep ${cid}
      docker rm --force --volumes ${cid}
    fi
  done
}

# The filter patterns must _NOT_ match the
# name of the katas-data-volume which is
# cyber-dojo-katas-DATA-CONTAINER.

collect_old_containers_and_volumes 'cyber_dojo_avatar_volume_runner_', 'DockerAvatarVolumeRunner'
collect_old_containers_and_volumes 'cyber_dojo_kata_volume_runner_',   'DockerKataVolumeRunner'
# DockerKataContainerRunner is self-collecting
