
version: '2.2'

services:
  collector:
    image: cyberdojo/collector
    init: true
    container_name: collector-server
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    build:
      context: .
      args:
        DOCKER_ENGINE_VERSION: 1.13.1
        SHA: ${SHA}
