
version: '2'

services:
  collector_server:
    image: cyberdojo/collector
    container_name: collector_server
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    build:
      context: .
