#!/bin/bash

volume_names=$(docker volume ls --quiet --filter 'name=cyber_dojo_')
for volume_name in ${volume_names}; do
  changers=$(docker run --rm -it -v ${volume_name}:/sandbox cyberdojo/collector sh -c "find /sandbox/** -mtime -7")
  if [ "${changers}" = "" ]; then
    docker volume rm ${volume_name}
  fi
done
